name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4  
        #- name: Set up Python
        #  uses: actions/setup-python@v4
        #  with:
        #    python-version: '3.10'
        #- name: Install dependencies
        #  run: |
        #    python -m pip install --upgrade pip
        #    pip install -r requirements.txt  
        #- name: Run tests
        #  run: python3 -m pytest tests/  

        #  build:
        #    needs: test  
        #    runs-on: ubuntu-latest  
        #    steps:
        #      - uses: actions/checkout@v4
        #      - name: Build the Docker image
        #        run: docker build . --file Dockerfile --tag option_chain_analysis_image:$(date +%s)
        #




