name: Infrastructure Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Initialize Terraform with S3 backend
        run: |
          terraform -chdir=infra/dev init \
            -backend-config="bucket=s2ranjan" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-2"

      - name: Terraform Plan
        id: plan
        run: |
          terraform -chdir=infra/dev plan -input=false -out=tfplan
          echo "plan_status=$?" >> $GITHUB_OUTPUT

      - name: Terraform Apply if Changes
        if: steps.plan.outputs.plan_status == 2
        run: terraform -chdir=infra/dev apply -input=false tfplan
