name: Infrastructure Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - uses: hashicorp/setup-terraform@v2

      # Cache Terraform state to avoid duplicates
      - name: Cache Terraform state
        uses: actions/cache@v3
        id: tf-state-cache
        with:
          path: infra/dev/terraform.tfstate
          key: tf-state-${{ github.run_id }}

      - name: Initialize Terraform
        run: terraform -chdir=infra/dev init

      - name: Apply Infrastructure
        run: terraform -chdir=infra/dev apply -auto-approve -input=false

      # Optionally, upload the latest state after apply
      - name: Upload latest Terraform state
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: infra/dev/terraform.tfstate
