name: Infrastructure Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write


    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Install Terraform first
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"  # Specify your desired version

      # Initialize with S3 backend
      - name: Initialize Terraform
        run: |
          cd infra/dev
          terraform init \
            -backend-config="bucket=s2ranjan" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-2"

      # Apply infrastructure changes
      - name: Apply Infrastructure
        run: |
          cd infra/dev
          terraform apply -auto-approve -input=false
