name: Infrastructure Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      actions: read  # Required for artifact access
      contents: read  # Required for checkout
      id-token: write # Required for OIDC if using AWS auth

    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2


      - name: Debug Workflow Info
        run: |
          echo "Triggering Workflow ID: ${{ github.event.workflow_run.id }}"
          echo "Current Workflow ID: ${{ github.run_id }}"

      - name: Find State Artifact
        id: find-artifact
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }},
            });
            
            console.log(`Found ${data.artifacts.length} artifacts`);
            data.artifacts.forEach(art => {
              console.log(`- ${art.name} (ID: ${art.id}, Size: ${art.size_in_bytes} bytes)`);
            });
            
            const artifact = data.artifacts.find(a => a.name === 'terraform-state');
            if (!artifact) {
              console.log('Artifact not found - checking if this is expected');
              core.setOutput('artifact_exists', 'false');
            } else {
              console.log(`Found terraform-state artifact (ID: ${artifact.id})`);
              core.setOutput('artifact_id', artifact.id);
              core.setOutput('artifact_exists', 'true');
            }


      # Download the artifact if it exists
      - name: Download State Artifact
        if: steps.find-artifact.outputs.artifact_exists == 'true'
        uses: actions/download-artifact@v4
        with:
          id: ${{ steps.find-artifact.outputs.artifact_id }}
          path: infra/dev/
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Rest of your workflow...
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform -chdir=infra/dev init

      - name: Apply Infrastructure
        run: terraform -chdir=infra/dev apply -auto-approve -input=false

      - name: Upload State Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: infra/dev/terraform.tfstate*
          if-no-files-found: error
          retention-days: 7



